### ISSUE TITLE
toegang repo

### ISSUE THREAD

**Issue by marknza** [joostlangeveldafmnl/course-r#2]
Ha @joostlangeveldafmnl, dank voor het geven van toegang tot jouw repository en veel plezier met de cursus straks!
(helaas ben ik zelf ziek en kan ik er de eerste keer niet bij zijn, maar we maken dan volgende week kennis)

groet,
Mark

**Comment by joostlangeveldafmnl** [comment]
Veel beterschap!

**Comment by marknza** [comment]
thanks, ik zag dat er ook zonder mij al goed gewerkt was :-)
